// Code generated by protoc-gen-go.
// source: _proto/paas/ci/openshift/service.proto
// DO NOT EDIT!

/*
Package openshift is a generated protocol buffer package.

It is generated from these files:
	_proto/paas/ci/openshift/service.proto

It has these top-level messages:
	EnterWorkspaceRequest
	EnterWorkspaceResponse
	QuitWorkspaceRequest
	QuitWorkspaceResponse
	CreateProjectRequest
	CreateProjectResponse
	DeleteProjectRequest
	DeleteProjectResponse
	BuildDockerImageRequest
	GitRepo
*/
package openshift

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EnterWorkspaceRequest struct {
	Username    string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Credentials string `protobuf:"bytes,2,opt,name=credentials" json:"credentials,omitempty"`
}

func (m *EnterWorkspaceRequest) Reset()                    { *m = EnterWorkspaceRequest{} }
func (m *EnterWorkspaceRequest) String() string            { return proto.CompactTextString(m) }
func (*EnterWorkspaceRequest) ProtoMessage()               {}
func (*EnterWorkspaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type EnterWorkspaceResponse struct {
	Identifier string `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
}

func (m *EnterWorkspaceResponse) Reset()                    { *m = EnterWorkspaceResponse{} }
func (m *EnterWorkspaceResponse) String() string            { return proto.CompactTextString(m) }
func (*EnterWorkspaceResponse) ProtoMessage()               {}
func (*EnterWorkspaceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type QuitWorkspaceRequest struct {
	Username   string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Identifier string `protobuf:"bytes,2,opt,name=identifier" json:"identifier,omitempty"`
}

func (m *QuitWorkspaceRequest) Reset()                    { *m = QuitWorkspaceRequest{} }
func (m *QuitWorkspaceRequest) String() string            { return proto.CompactTextString(m) }
func (*QuitWorkspaceRequest) ProtoMessage()               {}
func (*QuitWorkspaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type QuitWorkspaceResponse struct {
	Flag int64 `protobuf:"varint,1,opt,name=flag" json:"flag,omitempty"`
}

func (m *QuitWorkspaceResponse) Reset()                    { *m = QuitWorkspaceResponse{} }
func (m *QuitWorkspaceResponse) String() string            { return proto.CompactTextString(m) }
func (*QuitWorkspaceResponse) ProtoMessage()               {}
func (*QuitWorkspaceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type CreateProjectRequest struct {
	Identifier  string `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	ProjectID   string `protobuf:"bytes,2,opt,name=projectID" json:"projectID,omitempty"`
	ProjectName string `protobuf:"bytes,3,opt,name=projectName" json:"projectName,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
}

func (m *CreateProjectRequest) Reset()                    { *m = CreateProjectRequest{} }
func (m *CreateProjectRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateProjectRequest) ProtoMessage()               {}
func (*CreateProjectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type CreateProjectResponse struct {
	ApiVersion  string `protobuf:"bytes,1,opt,name=apiVersion" json:"apiVersion,omitempty"`
	Kind        string `protobuf:"bytes,2,opt,name=kind" json:"kind,omitempty"`
	ProjectJSON []byte `protobuf:"bytes,3,opt,name=projectJSON,proto3" json:"projectJSON,omitempty"`
}

func (m *CreateProjectResponse) Reset()                    { *m = CreateProjectResponse{} }
func (m *CreateProjectResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateProjectResponse) ProtoMessage()               {}
func (*CreateProjectResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type DeleteProjectRequest struct {
	Identifier string `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	ProjectID  string `protobuf:"bytes,2,opt,name=projectID" json:"projectID,omitempty"`
}

func (m *DeleteProjectRequest) Reset()                    { *m = DeleteProjectRequest{} }
func (m *DeleteProjectRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteProjectRequest) ProtoMessage()               {}
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type DeleteProjectResponse struct {
	Flag int64 `protobuf:"varint,1,opt,name=flag" json:"flag,omitempty"`
}

func (m *DeleteProjectResponse) Reset()                    { *m = DeleteProjectResponse{} }
func (m *DeleteProjectResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteProjectResponse) ProtoMessage()               {}
func (*DeleteProjectResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type BuildDockerImageRequest struct {
	DockerfileContent string `protobuf:"bytes,1,opt,name=dockerfileContent" json:"dockerfileContent,omitempty"`
	ContextArchive    string `protobuf:"bytes,2,opt,name=contextArchive" json:"contextArchive,omitempty"`
	Gitrepo           string `protobuf:"bytes,3,opt,name=gitrepo" json:"gitrepo,omitempty"`
	BinaryStream      string `protobuf:"bytes,4,opt,name=binaryStream" json:"binaryStream,omitempty"`
}

func (m *BuildDockerImageRequest) Reset()                    { *m = BuildDockerImageRequest{} }
func (m *BuildDockerImageRequest) String() string            { return proto.CompactTextString(m) }
func (*BuildDockerImageRequest) ProtoMessage()               {}
func (*BuildDockerImageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type GitRepo struct {
	Site        string `protobuf:"bytes,1,opt,name=site" json:"site,omitempty"`
	Uri         string `protobuf:"bytes,2,opt,name=uri" json:"uri,omitempty"`
	Ref         string `protobuf:"bytes,3,opt,name=ref" json:"ref,omitempty"`
	ContextPath string `protobuf:"bytes,4,opt,name=contextPath" json:"contextPath,omitempty"`
	DockerFile  string `protobuf:"bytes,5,opt,name=dockerFile" json:"dockerFile,omitempty"`
}

func (m *GitRepo) Reset()                    { *m = GitRepo{} }
func (m *GitRepo) String() string            { return proto.CompactTextString(m) }
func (*GitRepo) ProtoMessage()               {}
func (*GitRepo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func init() {
	proto.RegisterType((*EnterWorkspaceRequest)(nil), "paas.ci.openshift.EnterWorkspaceRequest")
	proto.RegisterType((*EnterWorkspaceResponse)(nil), "paas.ci.openshift.EnterWorkspaceResponse")
	proto.RegisterType((*QuitWorkspaceRequest)(nil), "paas.ci.openshift.QuitWorkspaceRequest")
	proto.RegisterType((*QuitWorkspaceResponse)(nil), "paas.ci.openshift.QuitWorkspaceResponse")
	proto.RegisterType((*CreateProjectRequest)(nil), "paas.ci.openshift.CreateProjectRequest")
	proto.RegisterType((*CreateProjectResponse)(nil), "paas.ci.openshift.CreateProjectResponse")
	proto.RegisterType((*DeleteProjectRequest)(nil), "paas.ci.openshift.DeleteProjectRequest")
	proto.RegisterType((*DeleteProjectResponse)(nil), "paas.ci.openshift.DeleteProjectResponse")
	proto.RegisterType((*BuildDockerImageRequest)(nil), "paas.ci.openshift.BuildDockerImageRequest")
	proto.RegisterType((*GitRepo)(nil), "paas.ci.openshift.GitRepo")
}

var fileDescriptor0 = []byte{
	// 555 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0xcd, 0x6e, 0x13, 0x31,
	0x10, 0x6e, 0x9a, 0x42, 0xc9, 0xf4, 0x47, 0xd4, 0x4a, 0x20, 0x8a, 0x10, 0xaa, 0xf6, 0x50, 0x82,
	0x40, 0x89, 0x04, 0x17, 0xae, 0xb4, 0x01, 0x54, 0x0e, 0xa5, 0x24, 0xfc, 0x48, 0x5c, 0x90, 0xbb,
	0x3b, 0x49, 0x86, 0x6c, 0x76, 0x8d, 0xed, 0x54, 0x70, 0xe6, 0x25, 0x78, 0x06, 0x24, 0xde, 0x91,
	0xb5, 0xd7, 0x49, 0x76, 0x13, 0x8b, 0x82, 0xd4, 0xdb, 0xf8, 0xf3, 0x78, 0xe6, 0x9b, 0x9f, 0xcf,
	0x70, 0xf4, 0x59, 0xc8, 0x54, 0xa7, 0x5d, 0xc1, 0xb9, 0xea, 0x86, 0xd4, 0x4d, 0x05, 0x26, 0x6a,
	0x4c, 0x43, 0xdd, 0x55, 0x28, 0x2f, 0x29, 0xc4, 0x8e, 0xbd, 0x67, 0x07, 0xc6, 0xa1, 0x13, 0x52,
	0x67, 0xe1, 0x10, 0xbc, 0x87, 0xc6, 0x8b, 0x44, 0xa3, 0xfc, 0x98, 0xca, 0x89, 0x12, 0x3c, 0xc4,
	0x3e, 0x7e, 0x9d, 0xa1, 0xd2, 0xac, 0x05, 0xb7, 0x66, 0xd9, 0xeb, 0x84, 0x4f, 0xb1, 0x59, 0x39,
	0xac, 0xb4, 0x6b, 0xfd, 0xc5, 0x99, 0x1d, 0xc2, 0x4e, 0x28, 0x31, 0xc2, 0x44, 0x13, 0x8f, 0x55,
	0x73, 0xd3, 0x5e, 0x17, 0xa1, 0xe0, 0x19, 0xdc, 0x59, 0x0d, 0xab, 0x44, 0x9a, 0x28, 0x64, 0xf7,
	0x01, 0xc8, 0xba, 0x0d, 0x09, 0xa5, 0x8b, 0x5c, 0x40, 0x82, 0x3e, 0xd4, 0xdf, 0xce, 0x48, 0xff,
	0x17, 0x9f, 0x72, 0xcc, 0xcd, 0xb5, 0x98, 0x8f, 0xa0, 0xb1, 0x12, 0xd3, 0x91, 0x61, 0xb0, 0x35,
	0x8c, 0xf9, 0xc8, 0x06, 0xac, 0xf6, 0xad, 0x1d, 0xfc, 0xac, 0x40, 0xfd, 0x44, 0x22, 0xd7, 0x78,
	0x2e, 0xd3, 0x2f, 0x18, 0xea, 0x39, 0x83, 0x2b, 0x98, 0xb3, 0x7b, 0x50, 0x13, 0xf9, 0x8b, 0xd3,
	0x9e, 0x23, 0xb1, 0x04, 0x4c, 0xcf, 0xdc, 0xe1, 0xcc, 0x94, 0x50, 0xcd, 0x7b, 0x56, 0x80, 0x8c,
	0x47, 0x84, 0x2a, 0x94, 0x24, 0x34, 0xa5, 0x49, 0x73, 0x2b, 0xf7, 0x28, 0x40, 0xc1, 0x14, 0x1a,
	0x2b, 0xcc, 0x96, 0x4d, 0xe5, 0x82, 0x3e, 0xa0, 0x54, 0xe6, 0xa5, 0xa3, 0xb6, 0x44, 0x4c, 0x9d,
	0x13, 0x4a, 0x22, 0xc7, 0xca, 0xda, 0x05, 0x42, 0xaf, 0x07, 0x6f, 0xce, 0x2c, 0xa1, 0xdd, 0x7e,
	0x11, 0x0a, 0xde, 0x41, 0xbd, 0x87, 0x31, 0x5e, 0x6f, 0x23, 0xcc, 0x30, 0x56, 0xa2, 0xfe, 0x65,
	0x18, 0xbf, 0x2b, 0x70, 0xf7, 0x78, 0x46, 0x71, 0xd4, 0x4b, 0xc3, 0x09, 0xca, 0xd3, 0x29, 0x1f,
	0x2d, 0x36, 0xe2, 0x31, 0x1c, 0x44, 0x16, 0x1d, 0x52, 0x8c, 0x27, 0x69, 0xb6, 0x6e, 0x89, 0x76,
	0x6c, 0xd6, 0x2f, 0xd8, 0x11, 0xec, 0x87, 0xc6, 0xfc, 0xa6, 0x9f, 0xcb, 0x70, 0x4c, 0x97, 0xe8,
	0x98, 0xad, 0xa0, 0xac, 0x09, 0xdb, 0x23, 0xd2, 0x12, 0x45, 0xea, 0x66, 0x34, 0x3f, 0xb2, 0x00,
	0x76, 0x2f, 0x28, 0xe1, 0xf2, 0xfb, 0x20, 0x3b, 0xf3, 0xa9, 0x1b, 0x50, 0x09, 0x0b, 0x7e, 0x54,
	0x60, 0xfb, 0x15, 0x65, 0x35, 0x65, 0xfe, 0x59, 0x3d, 0x8a, 0xf4, 0x7c, 0x5b, 0xad, 0xcd, 0x6e,
	0x43, 0x75, 0x26, 0xc9, 0xa5, 0x36, 0xa6, 0x41, 0x24, 0x0e, 0x5d, 0x2e, 0x63, 0x5a, 0x75, 0xe5,
	0x9c, 0xce, 0xb9, 0x1e, 0xcf, 0xf7, 0xa0, 0x00, 0x99, 0x01, 0xe4, 0x05, 0xbe, 0xcc, 0x0a, 0x6c,
	0xde, 0xc8, 0x07, 0xb0, 0x44, 0x9e, 0xfc, 0xaa, 0xc2, 0xde, 0x80, 0xa6, 0x22, 0xc6, 0x41, 0xae,
	0x7f, 0x36, 0x82, 0xfd, 0xb2, 0x1e, 0x59, 0xbb, 0xb3, 0xf6, 0x19, 0x74, 0xbc, 0x3f, 0x41, 0xeb,
	0xe1, 0x3f, 0x78, 0xe6, 0x23, 0x0c, 0x36, 0x58, 0x04, 0x7b, 0x25, 0xa9, 0xb1, 0x07, 0x9e, 0xd7,
	0x3e, 0x81, 0xb7, 0xda, 0x57, 0x3b, 0x16, 0xb3, 0x94, 0x84, 0xe0, 0xcd, 0xe2, 0x13, 0xb1, 0x37,
	0x8b, 0x57, 0x53, 0x79, 0x96, 0xd2, 0xa6, 0x7a, 0xb3, 0xf8, 0x14, 0xe2, 0xcd, 0xe2, 0x5d, 0xfa,
	0x60, 0xe3, 0x78, 0xe7, 0x53, 0x6d, 0xe1, 0x74, 0x71, 0xd3, 0x7e, 0xd4, 0x4f, 0xff, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x74, 0x6f, 0x8b, 0xfb, 0xd2, 0x05, 0x00, 0x00,
}
