apiVersion: v1
kind: BuildConfig
metadata:
    creationTimestamp: null
    labels:
      ci: buildconfig101
      name: buildconfig101
    name: buildconfig101
Spec:
  CompletionDeadlineSeconds: null
  Output:
    PushSecret: null
    To: null
  PostCommit:
    Args: null
    Command: null
    Script: ""
  Resources: {}
  Revision: null
  ServiceAccount: ""
  Source:
    Binary: null
    ContextDir: ""
    Dockerfile: null
    Git: null
    Images: null
    Secrets: null
    SourceSecret: null
  Strategy:
    CustomStrategy: null
    DockerStrategy: null
    SourceStrategy: null
  Triggers: null
Status:
  LastVersion: 0
