apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/build.name: netcat-http
  creationTimestamp: 2016-06-19T06:02:28Z
  labels:
    openshift.io/build.name: netcat-http
  name: netcat-http-build
  namespace: tangfeixiong
spec:
  containers:
  - args:
    - --loglevel=5
    env:
    - name: BUILD
      value: |
        {"kind":"Build","apiVersion":"v1","metadata":{"name":"netcat-http","namespace":"tangfeixiong","selfLink":"/oapi/v1/namespaces/tangfeixiong/builds/netcat-http","uid":"67593e22-35e3-11e6-b977-12fd6dcab3cd","resourceVersion":"153","creationTimestamp":"2016-06-19T06:02:28Z","labels":{"openshift.io/build-config.name":"tangfeixiong"},"annotations":{"openshift.io/build.number":"1"}},"spec":{"source":{"type":"Git","dockerfile":"FROM docker.io/alpine:edge\nRUN apk add --update netcat-openbsd \u0026\u0026 rm -rf /var/cache/apk/*\nCOPY entrypoint.sh /\nENTRYPOINT [\"/entrypoint.sh\"]\\nCMD [\"nc\"]","git":{"uri":"https://github.com/tangfeixiong/docker-nc.git","ref":"master"},"contextDir":"latest","secrets":null},"strategy":{"type":"Docker","dockerStrategy":{"from":{"kind":"DockerImage","name":"alpine:edge"}}},"output":{"to":{"kind":"DockerImage","name":"docker.io/tangfeixiong/nc-http-dev:latest"},"pushSecret":{"name":"tangfeixiong"}},"resources":{},"postCommit":{},"triggeredBy":null},"status":{"phase":"New","outputDockerImageReference":"docker.io/tangfeixiong/nc-http-dev:latest"}}
    - name: BUILD_LOGLEVEL
      value: "5"
    - name: SOURCE_REPOSITORY
      value: https://github.com/tangfeixiong/docker-nc.git
    - name: SOURCE_URI
      value: https://github.com/tangfeixiong/docker-nc.git
    - name: SOURCE_CONTEXT_DIR
      value: latest
    - name: SOURCE_REF
      value: master
    - name: ORIGIN_VERSION
      value: v1.3.0-alpha.1-39-gde8130a-dirty
    - name: PUSH_DOCKERCFG_PATH
      value: /var/run/secrets/openshift.io/push
    image: openshift/origin-docker-builder:v1.3.0-alpha.1
    imagePullPolicy: IfNotPresent
    name: docker-build
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-socket
    - mountPath: /var/run/secrets/openshift.io/push
      name: tangfeixiong-push
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-o4cdz
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: default-dockercfg-nr9yp
  nodeName: 172.17.4.50
  restartPolicy: Never
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - hostPath:
      path: /var/run/docker.sock
    name: docker-socket
  - name: tangfeixiong-push
    secret:
      secretName: tangfeixiong
  - name: default-token-o4cdz
    secret:
      secretName: default-token-o4cdz
status: {}
