apiVersion: v1
kind: SessionSecrets
secrets: 
# - authentication: "Signing secret, used to authenticate sessions using HMAC. Recommended to use a secret with 32 or 64 bytes." 
#   encryption: "Encrypting secret, used to encrypt sessions. Must be 16, 24, or 32 characters long, to select AES-128, AES-192, or AES-256." 
- authentication: "a 32 bytes authentication string"
  encryption: "a 16 characters!"
