// Code generated by protoc-gen-gogo.
// source: paas/ci/osopb3/docker-engine-api.proto
// DO NOT EDIT!

/*
	Package osopb3 is a generated protocol buffer package.

	It is generated from these files:
		paas/ci/osopb3/docker-engine-api.proto
		paas/ci/osopb3/grpc.proto
		paas/ci/osopb3/model.proto

	It has these top-level messages:
		DockerAuthConfig
		DockerConfigFile
		ProjectResponseDataArbitrary
		ProjectCreationRequestData
		ProjectCreationResponseData
		ProjectRetrieveRequestData
		ProjectRetrieveResponseData
		ProjectUpdationRequestData
		ProjectDeletionRequestData
		ProjectDeletionResponseData
		CreateOriginProjectRequest
		CreateOriginProjectResponse
		FindProjectRequest
		FindProjectResponse
		DeleteProjectRequest
		DeleteProjectResponse
		DockerBuildConfigRequestData
		DockerBuildConfigResponseData
		DockerBuildRequestData
		DockerBuildResponseData
		RawJSON
		StiBuildRequestData
		StiBuildResponseData
		RawData
		VersionRequestData
		VersionResponseData
		SourceControlUser
		GitSourceRevision
		SourceRevision
		BuildPostCommitSpec
		BuildOutput
		JenkinsPipelineBuildStrategy
		SecretSpec
		CustomBuildStrategy
		SourceBuildStrategy
		DockerBuildStrategy
		BuildStrategy
		SecretBuildSource
		ImageSourcePath
		ImageSource
		GitBuildSource
		BinaryBuildSource
		BuildSource
		OsoCommonSpec
		WebHookTrigger
		ImageChangeTrigger
		OsoBuildTriggerPolicy
		GenericWebHookCause
		GitHubWebHookCause
		ImageChangeCause
		OsoBuildTriggerCause
		OsoBuildStatus
*/
package osopb3

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import errors "errors"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// https://github.com/docker/engine-api/blob/master/types/auth.go
type DockerAuthConfig struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Auth     string `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	// Email is an optional value associated with the username.
	// This field is deprecated and will be removed in a later
	// version of docker.
	Email         string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	ServerAddress string `protobuf:"bytes,5,opt,name=serverAddress,proto3" json:"serverAddress,omitempty"`
	// IdentityToken is used to authenticate the user and get
	// an access token for the registry.
	IdentityToken string `protobuf:"bytes,6,opt,name=identityToken,proto3" json:"identityToken,omitempty"`
	// RegistryToken is a bearer token to be sent to a registry
	RegistryToken string `protobuf:"bytes,7,opt,name=registryToken,proto3" json:"registryToken,omitempty"`
}

func (m *DockerAuthConfig) Reset()                    { *m = DockerAuthConfig{} }
func (m *DockerAuthConfig) String() string            { return proto.CompactTextString(m) }
func (*DockerAuthConfig) ProtoMessage()               {}
func (*DockerAuthConfig) Descriptor() ([]byte, []int) { return fileDescriptorDockerEngineApi, []int{0} }

// https://github.com/docker/docker/blob/master/cliconfig/configfile/file.go
type DockerConfigFile struct {
	AuthConfigs      map[string]*DockerAuthConfig `protobuf:"bytes,1,rep,name=authConfigs" json:"authConfigs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
	HttpHeaders      map[string]string            `protobuf:"bytes,2,rep,name=httpHeaders" json:"httpHeaders,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	PsFormat         string                       `protobuf:"bytes,3,opt,name=psFormat,proto3" json:"psFormat,omitempty"`
	ImagesFormat     string                       `protobuf:"bytes,4,opt,name=imagesFormat,proto3" json:"imagesFormat,omitempty"`
	NetworksFormat   string                       `protobuf:"bytes,5,opt,name=networksFormat,proto3" json:"networksFormat,omitempty"`
	VolumesFormat    string                       `protobuf:"bytes,6,opt,name=volumesFormat,proto3" json:"volumesFormat,omitempty"`
	DetachKeys       string                       `protobuf:"bytes,7,opt,name=detachKeys,proto3" json:"detachKeys,omitempty"`
	CredentialsStore string                       `protobuf:"bytes,8,opt,name=credentialsStore,proto3" json:"credentialsStore,omitempty"`
	Filename         string                       `protobuf:"bytes,9,opt,name=filename,proto3" json:"filename,omitempty"`
}

func (m *DockerConfigFile) Reset()                    { *m = DockerConfigFile{} }
func (m *DockerConfigFile) String() string            { return proto.CompactTextString(m) }
func (*DockerConfigFile) ProtoMessage()               {}
func (*DockerConfigFile) Descriptor() ([]byte, []int) { return fileDescriptorDockerEngineApi, []int{1} }

func (m *DockerConfigFile) GetAuthConfigs() map[string]*DockerAuthConfig {
	if m != nil {
		return m.AuthConfigs
	}
	return nil
}

func (m *DockerConfigFile) GetHttpHeaders() map[string]string {
	if m != nil {
		return m.HttpHeaders
	}
	return nil
}

func init() {
	proto.RegisterType((*DockerAuthConfig)(nil), "paas.ci.osopb3.DockerAuthConfig")
	proto.RegisterType((*DockerConfigFile)(nil), "paas.ci.osopb3.DockerConfigFile")
}
func (m *DockerAuthConfig) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *DockerAuthConfig) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Username) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintDockerEngineApi(data, i, uint64(len(m.Username)))
		i += copy(data[i:], m.Username)
	}
	if len(m.Password) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintDockerEngineApi(data, i, uint64(len(m.Password)))
		i += copy(data[i:], m.Password)
	}
	if len(m.Auth) > 0 {
		data[i] = 0x1a
		i++
		i = encodeVarintDockerEngineApi(data, i, uint64(len(m.Auth)))
		i += copy(data[i:], m.Auth)
	}
	if len(m.Email) > 0 {
		data[i] = 0x22
		i++
		i = encodeVarintDockerEngineApi(data, i, uint64(len(m.Email)))
		i += copy(data[i:], m.Email)
	}
	if len(m.ServerAddress) > 0 {
		data[i] = 0x2a
		i++
		i = encodeVarintDockerEngineApi(data, i, uint64(len(m.ServerAddress)))
		i += copy(data[i:], m.ServerAddress)
	}
	if len(m.IdentityToken) > 0 {
		data[i] = 0x32
		i++
		i = encodeVarintDockerEngineApi(data, i, uint64(len(m.IdentityToken)))
		i += copy(data[i:], m.IdentityToken)
	}
	if len(m.RegistryToken) > 0 {
		data[i] = 0x3a
		i++
		i = encodeVarintDockerEngineApi(data, i, uint64(len(m.RegistryToken)))
		i += copy(data[i:], m.RegistryToken)
	}
	return i, nil
}

func (m *DockerConfigFile) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *DockerConfigFile) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.AuthConfigs) > 0 {
		for k, _ := range m.AuthConfigs {
			data[i] = 0xa
			i++
			v := m.AuthConfigs[k]
			if v == nil {
				return 0, errors.New("proto: map has nil element")
			}
			msgSize := v.Size()
			mapSize := 1 + len(k) + sovDockerEngineApi(uint64(len(k))) + 1 + msgSize + sovDockerEngineApi(uint64(msgSize))
			i = encodeVarintDockerEngineApi(data, i, uint64(mapSize))
			data[i] = 0xa
			i++
			i = encodeVarintDockerEngineApi(data, i, uint64(len(k)))
			i += copy(data[i:], k)
			data[i] = 0x12
			i++
			i = encodeVarintDockerEngineApi(data, i, uint64(v.Size()))
			n1, err := v.MarshalTo(data[i:])
			if err != nil {
				return 0, err
			}
			i += n1
		}
	}
	if len(m.HttpHeaders) > 0 {
		for k, _ := range m.HttpHeaders {
			data[i] = 0x12
			i++
			v := m.HttpHeaders[k]
			mapSize := 1 + len(k) + sovDockerEngineApi(uint64(len(k))) + 1 + len(v) + sovDockerEngineApi(uint64(len(v)))
			i = encodeVarintDockerEngineApi(data, i, uint64(mapSize))
			data[i] = 0xa
			i++
			i = encodeVarintDockerEngineApi(data, i, uint64(len(k)))
			i += copy(data[i:], k)
			data[i] = 0x12
			i++
			i = encodeVarintDockerEngineApi(data, i, uint64(len(v)))
			i += copy(data[i:], v)
		}
	}
	if len(m.PsFormat) > 0 {
		data[i] = 0x1a
		i++
		i = encodeVarintDockerEngineApi(data, i, uint64(len(m.PsFormat)))
		i += copy(data[i:], m.PsFormat)
	}
	if len(m.ImagesFormat) > 0 {
		data[i] = 0x22
		i++
		i = encodeVarintDockerEngineApi(data, i, uint64(len(m.ImagesFormat)))
		i += copy(data[i:], m.ImagesFormat)
	}
	if len(m.NetworksFormat) > 0 {
		data[i] = 0x2a
		i++
		i = encodeVarintDockerEngineApi(data, i, uint64(len(m.NetworksFormat)))
		i += copy(data[i:], m.NetworksFormat)
	}
	if len(m.VolumesFormat) > 0 {
		data[i] = 0x32
		i++
		i = encodeVarintDockerEngineApi(data, i, uint64(len(m.VolumesFormat)))
		i += copy(data[i:], m.VolumesFormat)
	}
	if len(m.DetachKeys) > 0 {
		data[i] = 0x3a
		i++
		i = encodeVarintDockerEngineApi(data, i, uint64(len(m.DetachKeys)))
		i += copy(data[i:], m.DetachKeys)
	}
	if len(m.CredentialsStore) > 0 {
		data[i] = 0x42
		i++
		i = encodeVarintDockerEngineApi(data, i, uint64(len(m.CredentialsStore)))
		i += copy(data[i:], m.CredentialsStore)
	}
	if len(m.Filename) > 0 {
		data[i] = 0x4a
		i++
		i = encodeVarintDockerEngineApi(data, i, uint64(len(m.Filename)))
		i += copy(data[i:], m.Filename)
	}
	return i, nil
}

func encodeFixed64DockerEngineApi(data []byte, offset int, v uint64) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	data[offset+4] = uint8(v >> 32)
	data[offset+5] = uint8(v >> 40)
	data[offset+6] = uint8(v >> 48)
	data[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32DockerEngineApi(data []byte, offset int, v uint32) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintDockerEngineApi(data []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		data[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	data[offset] = uint8(v)
	return offset + 1
}
func (m *DockerAuthConfig) Size() (n int) {
	var l int
	_ = l
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovDockerEngineApi(uint64(l))
	}
	l = len(m.Password)
	if l > 0 {
		n += 1 + l + sovDockerEngineApi(uint64(l))
	}
	l = len(m.Auth)
	if l > 0 {
		n += 1 + l + sovDockerEngineApi(uint64(l))
	}
	l = len(m.Email)
	if l > 0 {
		n += 1 + l + sovDockerEngineApi(uint64(l))
	}
	l = len(m.ServerAddress)
	if l > 0 {
		n += 1 + l + sovDockerEngineApi(uint64(l))
	}
	l = len(m.IdentityToken)
	if l > 0 {
		n += 1 + l + sovDockerEngineApi(uint64(l))
	}
	l = len(m.RegistryToken)
	if l > 0 {
		n += 1 + l + sovDockerEngineApi(uint64(l))
	}
	return n
}

func (m *DockerConfigFile) Size() (n int) {
	var l int
	_ = l
	if len(m.AuthConfigs) > 0 {
		for k, v := range m.AuthConfigs {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
			}
			mapEntrySize := 1 + len(k) + sovDockerEngineApi(uint64(len(k))) + 1 + l + sovDockerEngineApi(uint64(l))
			n += mapEntrySize + 1 + sovDockerEngineApi(uint64(mapEntrySize))
		}
	}
	if len(m.HttpHeaders) > 0 {
		for k, v := range m.HttpHeaders {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovDockerEngineApi(uint64(len(k))) + 1 + len(v) + sovDockerEngineApi(uint64(len(v)))
			n += mapEntrySize + 1 + sovDockerEngineApi(uint64(mapEntrySize))
		}
	}
	l = len(m.PsFormat)
	if l > 0 {
		n += 1 + l + sovDockerEngineApi(uint64(l))
	}
	l = len(m.ImagesFormat)
	if l > 0 {
		n += 1 + l + sovDockerEngineApi(uint64(l))
	}
	l = len(m.NetworksFormat)
	if l > 0 {
		n += 1 + l + sovDockerEngineApi(uint64(l))
	}
	l = len(m.VolumesFormat)
	if l > 0 {
		n += 1 + l + sovDockerEngineApi(uint64(l))
	}
	l = len(m.DetachKeys)
	if l > 0 {
		n += 1 + l + sovDockerEngineApi(uint64(l))
	}
	l = len(m.CredentialsStore)
	if l > 0 {
		n += 1 + l + sovDockerEngineApi(uint64(l))
	}
	l = len(m.Filename)
	if l > 0 {
		n += 1 + l + sovDockerEngineApi(uint64(l))
	}
	return n
}

func sovDockerEngineApi(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozDockerEngineApi(x uint64) (n int) {
	return sovDockerEngineApi(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DockerAuthConfig) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDockerEngineApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DockerAuthConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DockerAuthConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDockerEngineApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDockerEngineApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Password", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDockerEngineApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDockerEngineApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Password = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Auth", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDockerEngineApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDockerEngineApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Auth = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Email", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDockerEngineApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDockerEngineApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Email = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDockerEngineApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDockerEngineApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServerAddress = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IdentityToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDockerEngineApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDockerEngineApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IdentityToken = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistryToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDockerEngineApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDockerEngineApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegistryToken = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDockerEngineApi(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDockerEngineApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DockerConfigFile) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDockerEngineApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DockerConfigFile: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DockerConfigFile: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthConfigs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDockerEngineApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDockerEngineApi
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var keykey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDockerEngineApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				keykey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			var stringLenmapkey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDockerEngineApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLenmapkey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLenmapkey := int(stringLenmapkey)
			if intStringLenmapkey < 0 {
				return ErrInvalidLengthDockerEngineApi
			}
			postStringIndexmapkey := iNdEx + intStringLenmapkey
			if postStringIndexmapkey > l {
				return io.ErrUnexpectedEOF
			}
			mapkey := string(data[iNdEx:postStringIndexmapkey])
			iNdEx = postStringIndexmapkey
			var valuekey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDockerEngineApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				valuekey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			var mapmsglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDockerEngineApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				mapmsglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if mapmsglen < 0 {
				return ErrInvalidLengthDockerEngineApi
			}
			postmsgIndex := iNdEx + mapmsglen
			if mapmsglen < 0 {
				return ErrInvalidLengthDockerEngineApi
			}
			if postmsgIndex > l {
				return io.ErrUnexpectedEOF
			}
			mapvalue := &DockerAuthConfig{}
			if err := mapvalue.Unmarshal(data[iNdEx:postmsgIndex]); err != nil {
				return err
			}
			iNdEx = postmsgIndex
			if m.AuthConfigs == nil {
				m.AuthConfigs = make(map[string]*DockerAuthConfig)
			}
			m.AuthConfigs[mapkey] = mapvalue
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HttpHeaders", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDockerEngineApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDockerEngineApi
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var keykey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDockerEngineApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				keykey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			var stringLenmapkey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDockerEngineApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLenmapkey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLenmapkey := int(stringLenmapkey)
			if intStringLenmapkey < 0 {
				return ErrInvalidLengthDockerEngineApi
			}
			postStringIndexmapkey := iNdEx + intStringLenmapkey
			if postStringIndexmapkey > l {
				return io.ErrUnexpectedEOF
			}
			mapkey := string(data[iNdEx:postStringIndexmapkey])
			iNdEx = postStringIndexmapkey
			var valuekey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDockerEngineApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				valuekey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			var stringLenmapvalue uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDockerEngineApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLenmapvalue |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLenmapvalue := int(stringLenmapvalue)
			if intStringLenmapvalue < 0 {
				return ErrInvalidLengthDockerEngineApi
			}
			postStringIndexmapvalue := iNdEx + intStringLenmapvalue
			if postStringIndexmapvalue > l {
				return io.ErrUnexpectedEOF
			}
			mapvalue := string(data[iNdEx:postStringIndexmapvalue])
			iNdEx = postStringIndexmapvalue
			if m.HttpHeaders == nil {
				m.HttpHeaders = make(map[string]string)
			}
			m.HttpHeaders[mapkey] = mapvalue
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PsFormat", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDockerEngineApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDockerEngineApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PsFormat = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ImagesFormat", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDockerEngineApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDockerEngineApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ImagesFormat = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworksFormat", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDockerEngineApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDockerEngineApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NetworksFormat = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VolumesFormat", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDockerEngineApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDockerEngineApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VolumesFormat = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DetachKeys", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDockerEngineApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDockerEngineApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DetachKeys = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CredentialsStore", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDockerEngineApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDockerEngineApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CredentialsStore = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Filename", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDockerEngineApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDockerEngineApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Filename = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDockerEngineApi(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDockerEngineApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDockerEngineApi(data []byte) (n int, err error) {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDockerEngineApi
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDockerEngineApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if data[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDockerEngineApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthDockerEngineApi
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowDockerEngineApi
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := data[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipDockerEngineApi(data[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthDockerEngineApi = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDockerEngineApi   = fmt.Errorf("proto: integer overflow")
)

var fileDescriptorDockerEngineApi = []byte{
	// 517 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x53, 0x4f, 0x6f, 0xd3, 0x30,
	0x1c, 0x25, 0xeb, 0x1f, 0x56, 0x17, 0xa6, 0xc8, 0xea, 0x21, 0xaa, 0x50, 0x35, 0x55, 0x68, 0x1a,
	0x48, 0x4b, 0xc4, 0x26, 0x21, 0xc4, 0x01, 0x69, 0x83, 0x4d, 0x93, 0x10, 0x97, 0x8e, 0x0b, 0x9c,
	0x70, 0x93, 0x5f, 0x53, 0xab, 0x89, 0x1d, 0x6c, 0xa7, 0xa8, 0xdf, 0x84, 0x8f, 0xc4, 0x91, 0x03,
	0x1f, 0x00, 0x81, 0xc4, 0xe7, 0xc0, 0xb1, 0x93, 0x36, 0x09, 0x3d, 0x70, 0x88, 0x94, 0xdf, 0xfb,
	0x3d, 0xbf, 0x9f, 0xdf, 0xb3, 0x8d, 0x4e, 0x32, 0x42, 0x64, 0x10, 0xd2, 0x80, 0x4b, 0x9e, 0xcd,
	0x2f, 0x82, 0x88, 0x87, 0x2b, 0x10, 0x67, 0xc0, 0x62, 0xca, 0xe0, 0x8c, 0x64, 0xd4, 0xcf, 0x04,
	0x57, 0x1c, 0x1f, 0x15, 0x3c, 0x3f, 0xa4, 0xbe, 0xe5, 0x8d, 0x1f, 0xc5, 0x9c, 0xc7, 0x09, 0x04,
	0x9a, 0x11, 0x10, 0xc6, 0xb8, 0x22, 0x8a, 0x72, 0x26, 0x2d, 0x7b, 0xfa, 0xc7, 0x41, 0xee, 0x1b,
	0xa3, 0x74, 0x99, 0xab, 0xe5, 0x6b, 0xce, 0x16, 0x34, 0xc6, 0x63, 0x74, 0x98, 0x4b, 0x10, 0x8c,
	0xa4, 0xe0, 0x39, 0xc7, 0xce, 0xe9, 0x60, 0xb6, 0xad, 0x8b, 0x5e, 0x46, 0xa4, 0xfc, 0xc2, 0x45,
	0xe4, 0x1d, 0xd8, 0x5e, 0x55, 0x63, 0x8c, 0xba, 0x44, 0xab, 0x78, 0x1d, 0x83, 0x9b, 0x7f, 0x3c,
	0x42, 0x3d, 0x48, 0x09, 0x4d, 0xbc, 0xae, 0x01, 0x6d, 0x81, 0x1f, 0xa3, 0x87, 0x5a, 0x70, 0xad,
	0xa7, 0x46, 0x91, 0x00, 0x29, 0xbd, 0x9e, 0xe9, 0x36, 0xc1, 0x82, 0x45, 0x23, 0x60, 0x8a, 0xaa,
	0xcd, 0x7b, 0xbe, 0x02, 0xe6, 0xf5, 0x2d, 0xab, 0x01, 0x16, 0x2c, 0x01, 0x31, 0x95, 0x4a, 0x94,
	0xac, 0xfb, 0x96, 0xd5, 0x00, 0xa7, 0x3f, 0xba, 0x95, 0x51, 0x6b, 0xf2, 0x86, 0x26, 0x80, 0xef,
	0xd0, 0x90, 0x6c, 0x6d, 0x4b, 0xed, 0xb5, 0x73, 0x3a, 0x3c, 0x7f, 0xe6, 0x37, 0x13, 0xf4, 0xdb,
	0xcb, 0xfc, 0x5d, 0x54, 0xf2, 0x9a, 0xe9, 0x09, 0xb3, 0xba, 0x4a, 0x21, 0xba, 0x54, 0x2a, 0xbb,
	0x05, 0x12, 0x81, 0x90, 0x3a, 0xa4, 0xff, 0x13, 0xbd, 0xdd, 0xad, 0x29, 0x45, 0x6b, 0x2a, 0x26,
	0x76, 0x79, 0xc3, 0x45, 0x4a, 0x54, 0x19, 0xef, 0xb6, 0xc6, 0x53, 0xf4, 0x80, 0xa6, 0x24, 0x86,
	0xaa, 0x6f, 0x93, 0x6e, 0x60, 0xf8, 0x04, 0x1d, 0x31, 0x50, 0xfa, 0x94, 0x56, 0x15, 0xcb, 0x26,
	0xde, 0x42, 0x8b, 0x30, 0xd7, 0x3c, 0xc9, 0xd3, 0xad, 0x58, 0x19, 0x79, 0x03, 0xc4, 0x13, 0x84,
	0x22, 0x50, 0x24, 0x5c, 0xbe, 0x85, 0x8d, 0x2c, 0xf3, 0xae, 0x21, 0xf8, 0x29, 0x72, 0x43, 0x01,
	0xe6, 0x94, 0x48, 0x22, 0xef, 0x14, 0x17, 0xe0, 0x1d, 0x1a, 0xd6, 0x3f, 0x78, 0xe1, 0x6c, 0xa1,
	0xfd, 0x9b, 0xcb, 0x36, 0xb0, 0xce, 0xaa, 0x7a, 0xfc, 0x09, 0xb9, 0xed, 0xac, 0xb1, 0x8b, 0x3a,
	0x2b, 0xd8, 0x94, 0xf7, 0xb2, 0xf8, 0xc5, 0xcf, 0x51, 0x6f, 0x4d, 0x92, 0x1c, 0xcc, 0x7d, 0x1c,
	0x9e, 0x1f, 0xef, 0x8f, 0x7a, 0x27, 0x34, 0xb3, 0xf4, 0x97, 0x07, 0x2f, 0x9c, 0xf1, 0x2b, 0xe4,
	0xb6, 0x83, 0xdf, 0x33, 0x61, 0x54, 0x9f, 0x30, 0xa8, 0xad, 0xbf, 0xfa, 0xf0, 0xed, 0xd7, 0xc4,
	0xf9, 0xae, 0xbf, 0x9f, 0xfa, 0xfb, 0xfa, 0x7b, 0x72, 0x0f, 0x3d, 0x09, 0x79, 0xea, 0x7f, 0xa6,
	0x2c, 0xde, 0xe4, 0x84, 0x71, 0xbd, 0x0f, 0x6d, 0xd2, 0xb7, 0x6f, 0xd0, 0x3c, 0xb9, 0x79, 0xbe,
	0x28, 0x37, 0x76, 0x35, 0xb2, 0x3b, 0xbb, 0x36, 0x4f, 0xf8, 0x32, 0xa3, 0xef, 0x78, 0x04, 0xc9,
	0xc7, 0xbe, 0xed, 0xce, 0xfb, 0x86, 0x7e, 0xf1, 0x37, 0x00, 0x00, 0xff, 0xff, 0x52, 0x84, 0xee,
	0x38, 0xf9, 0x03, 0x00, 0x00,
}
